- name: Create /microsites
  file: state=directory path=/microsites mode=0775 owner=vagrant group=vagrant

- name: Create mysql database for microsites
  mysql_db:
    name: microsites
    state: present

- name: Create mysql user for microsites
  mysql_user:
    name: microsites
    host: localhost
    password: "{{ lookup('password', 'credentials/mysql/microsites length=15') }}"
    priv: "microsites.*:ALL"
    state: present

- name: Create apache site-available
  copy:
    src: roles/microsites/files/apache2/sites-available/001-microsites.conf
    dest: /etc/apache2/sites-available/001-microsites.conf
    mode: 0664
    owner: root
    group: root
  notify: apache reload

- name: Remove the default vhost config
  file: state=absent path=/etc/apache2/sites-enabled/000-default.conf
  notify: apache reload

- name: Link the microsites vhost config
  file:
    dest: /etc/apache2/sites-enabled/001-microsites.conf
    src: ../sites-available/001-microsites.conf
    owner: root
    group: root
    state: link
  notify: apache reload

# This is handled better in ansible 2.1. I'm on 2.0.0.2 currently.
# http://chaosmail.github.io/programming/2015/03/04/install-deb-packages-in-ansible/
- name: Check if php-wpcli is installed
  command: dpkg-query -f '${Version}' -W php-wpcli
  register: php_wpcli_check_deb
  failed_when: php_wpcli_check_deb.rc > 1
  changed_when: php_wpcli_check_deb.rc == 1

- name: Download php-wpcli
  get_url:
    url="https://github.com/wp-cli/builds/raw/gh-pages/deb/php-wpcli_1.1.0_all.deb"
    dest="/tmp/php-wpcli.deb"
  when:
    - php_wpcli_check_deb.rc == 1
    - php_wpcli_check_deb.stdout != '1.1.0'

- name: Install php-wpcli
  apt: deb="/tmp/php-wpcli.deb"
  become: true
  when:
    - php_wpcli_check_deb.rc == 1
    - php_wpcli_check_deb.stdout != '1.1.0'
