---
- name: Install apache and modules
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - php5-cli
    - apache2
    - php5-cgi
    - php5
    - libapache2-mod-php5
    - libapache2-mod-webauthldap
